### ISSUE TITLE
Confusing about Fig.4 results

### ISSUE THREAD

**Issue by MarkDeng1** [microsoft/DPSDA#5]
Hi authors,

Thank you for your excellent work.

I have a question regarding Figure 4. It shows that the FID increases as epsilon decreases (especially when epsilon is below 1). However, considering the DP added, it only affects the number of votes. Therefore, regardless of which synthetic data is sampled and sent to the VARIATION API, the generation quality should remain unchanged (since DP only affects the sampling probability P_t). 

Best regards,
Mark

**Comment by fjxmlzn** [comment]
Thank you for your question! 

I want to clarify two things: (1) Which parameters affect epsilon, (2) What information FID captures

## (1) Which parameters affect epsilon


* Sigma in Algorithm 2 (the scale of the Gaussian noise added to the histogram) affects epsilon. Larger sigma (i.e., more noise) gives smaller epsion (i.e., better privacy).
* T in Algorithm 1 (the number of iterations) affects epsilon. Smaller T (i.e., fewer iteration) gives smaller epsilon (i.e., better privacy)

Given a privacy budget, we can tune both parameters. In Figure 11 in the appendix, we show the joint effects of these two parameters. Each line there corresponds to the same sigma and different T.

## (2) What information FID captures

FID is usually described as "image quality", but it actually captures how close the images are to the ground-truth ones in distribution. For example, if one dataset is photos of dogs and the other is photos of cats. Both sets are realistic, but the FID score would be high. 

As you said, changing sigma could influence the noisy votes, thus influencing which synthetic data is sampled and sent to VARIATION API. This will influence the distribution of of the synthetic samples and thus the FID score. For example, let's say the private dataset is photos of cats. The histogram would have put high votes on synthetic cats, but due to the added Gaussian noise, the histogram puts some weights on synthetic dogs, and generate more dogs through VARIATION API. The FID score would then be higher than if only synthetic cats are selected and sent to VARIATION API.

Feel free to reopen the issue if it is not clear!

**Comment by schlevik** [comment]
I would also be interested in how you produced the plots in Figures 4/11.

From what I could gather from the paper, you use the fact that the Gaussian mechanism is $\mu$-GDP and therefore the total noise $\sigma_{T}$ for the composition of $T$ iterations should be $\sigma_T=\frac{\sigma}{\sqrt{n}}$. You then point in the paper to [Balle and Wang (2018)](https://arxiv.org/pdf/1805.06530) to obtain $\epsilon$ and $\delta$ from $\sigma$.
I can see how you would do it the other way round, obtain per-iteration $\sigma$ from a given privacy budget $\epsilon$ (and $\delta$) for all iterations $T$, since their algorithm calibrates the noise level given $\epsilon$, $\delta$ and sensitivity (1 for your algorithm), i.e. $\sigma = agm(\epsilon, \delta, 1) \cdot \sqrt{T}$, e.g. [using their implementation](https://github.com/BorjaBalle/analytic-gaussian-mechanism/blob/master/agm-example.py) of agm. But I don't immediately see how you compute $\epsilon$ for a given $\sigma$, since that would require inverting the agm algorithm wrt $\epsilon$. Do you just numerically search for $\epsilon$ for agm to yield $\sigma$ close enough to $\\{5,10,20\\}\cdot\sqrt{2}$? Or did I misunderstand something?

Many thanks in advance,

BW

**Comment by fjxmlzn** [comment]
@schlevik The `compute_epsilon` function in https://github.com/AI-secure/aug-pe/blob/main/notebook/dp_budget.ipynb is how we compute epsilon given noise std $\sigma$ (`noise_multiplier`), number of iterations T (`num_steps`), and DP `delta`.

Let me know if you have any questions!

**Comment by schlevik** [comment]
Cool, got it - so you're solving for optimal $\epsilon$ given $\delta$ and $\sigma = \frac{sens}{\mu}$ with equation (6) from [Balle and Wang (2018)](https://arxiv.org/pdf/1805.06530). That's of course more elegant.

Thank you!
